[octranspo]
# OC Transpo's API endpoint
endpoint = "https://api.octranspo1.com/v2.0/GetNextTripsForStopAllRoutes"
# OC Tranpo API key
api_key = "508a0741b6945609192422d77f3a1da4"
# OC Transpo app id
app_id = "13d12d72"

[google_cloud]
# Maps API key
api_key = "AIzaSyB1ha-Cb9kOv0dPi-mBZQ4JHukDRVEJ4ME"

[server]
# Port string used in http.ListenAndServe
port = ":3001"
# Enable CORS
cors = true
# Enable GraphQL playground
playground = true
# Where the data set is located
dataset = "./data"