[octranspo]
# OC Transpo's API endpoint
endpoint = "https://api.octranspo1.com/v2.0/GetNextTripsForStopAllRoutes"
# OC Tranpo API key
api_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# OC Transpo app id
app_id = "xxxxxxxxxxxxxx"

[google_cloud]
# Maps API key
api_key = "AIzaSyDnH87oA5pYUpa6o-OpkjUtZVxVBkosRPA"

[server]
# Port string used in http.ListenAndServe
port = ":3000"
# Enable CORS
cors = true
# Enable GraphQL playground
playground = true
# Where the data set is located
dataset = "./data"