// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"fmt"
	"io"
	"strconv"
)

type RouteType string

const (
	RouteTypeBus   RouteType = "BUS"
	RouteTypeTrain RouteType = "TRAIN"
)

var AllRouteType = []RouteType{
	RouteTypeBus,
	RouteTypeTrain,
}

func (e RouteType) IsValid() bool {
	switch e {
	case RouteTypeBus, RouteTypeTrain:
		return true
	}
	return false
}

func (e RouteType) String() string {
	return string(e)
}

func (e *RouteType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RouteType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RouteType", str)
	}
	return nil
}

func (e RouteType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
